name: Test

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install black flake8 mypy pytest
      - name: Check code formatting with black
        run: python -m black --check pytenki/
      - name: Lint code with flake8
        run: python -m flake8 pytenki/
      - name: Lint code with mypy
        run: python -m mypy pytenki/
      - name: Run test suite with pytest
        run: python -m pytest tests/
